version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_USER=swingkid
      - POSTGRES_PASSWORD=myshoppw
  web:
    build: .
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - POSTGRES_DB=shop
      - POSTGRES_USER=swingkid
      - POSTGRES_PASSWORD=myshoppw
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
